[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "audio-fp"
version = "0.1.0"
description = "Audio fingerprint matching with microphone and serial output"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "pydub",
  "scipy",
  "matplotlib",
  "sounddevice",
  "pyserial"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
